# Render Deploy — Single Service (Custom Bundler)
services:
  - type: web
    name: xdc-subs-app
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_WEB3AUTH_CLIENT_ID
        sync: false
      - key: NEXT_PUBLIC_APOTHEM_RPC_URL
        value: https://erpc.apothem.network
      - key: NEXT_PUBLIC_CHAIN_ID
        value: "51"
      - key: NEXT_PUBLIC_ENTRYPOINT_ADDRESS
        value: "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
      - key: NEXT_PUBLIC_SIMPLE_ACCOUNT_FACTORY_ADDRESS
        value: "0x91E60e0613810449d098b0b5Ec8b51A0FE8c8985"
      - key: NEXT_PUBLIC_SUBSCRIPTION_MANAGER
        value: "0xe8271C9Bc2255A41cd2AB53FbfB69CE4B5f3032E"
      - key: NEXT_PUBLIC_PAYMASTER_ADDRESS
        value: "0x8361Fae5A25e71C2E1db35cDE13E7150bB7b1a42"
      - key: NEXT_PUBLIC_GAS_PAYMASTER_ADDRESS
        value: "0x12C8a71e89A482F8C5D22AAaE1e58b7Bb35a5489"
      - key: WEB3AUTH_CLIENT_ID
        sync: false
      - key: PAYMASTER_PRIVATE_KEY
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: BUNDLER_PRIVATE_KEY
        sync: false