type PublicEnvKey =
  | "NEXT_PUBLIC_WEB3AUTH_CLIENT_ID"
  | "NEXT_PUBLIC_ARKA_API_KEY"
  | "NEXT_PUBLIC_BUNDLER_URL"
  | "NEXT_PUBLIC_APOTHEM_RPC_URL"
  | "NEXT_PUBLIC_CHAIN_ID"
  | "NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS"
  | "NEXT_PUBLIC_TOKEN_A_ADDRESS"
  | "NEXT_PUBLIC_TOKEN_B_ADDRESS"
  | "NEXT_PUBLIC_EXPLORER_URL";

function getPublicEnv(key: PublicEnvKey): string {
  const value = process.env[key];
  if (!value) {
    throw new Error(`Missing environment variable: ${key}`);
  }
  return value;
}

export const env = {
  NEXT_PUBLIC_WEB3AUTH_CLIENT_ID: getPublicEnv("NEXT_PUBLIC_WEB3AUTH_CLIENT_ID"),
  NEXT_PUBLIC_ARKA_API_KEY: getPublicEnv("NEXT_PUBLIC_ARKA_API_KEY"),
  NEXT_PUBLIC_BUNDLER_URL: getPublicEnv("NEXT_PUBLIC_BUNDLER_URL"),
  NEXT_PUBLIC_APOTHEM_RPC_URL: getPublicEnv("NEXT_PUBLIC_APOTHEM_RPC_URL"),
  NEXT_PUBLIC_CHAIN_ID: Number(getPublicEnv("NEXT_PUBLIC_CHAIN_ID")),
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS: getPublicEnv("NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS"),
  NEXT_PUBLIC_TOKEN_A_ADDRESS: getPublicEnv("NEXT_PUBLIC_TOKEN_A_ADDRESS"),
  NEXT_PUBLIC_TOKEN_B_ADDRESS: getPublicEnv("NEXT_PUBLIC_TOKEN_B_ADDRESS"),
  NEXT_PUBLIC_EXPLORER_URL: getPublicEnv("NEXT_PUBLIC_EXPLORER_URL"),
};
